sudo: false
language: node_js
node_js:
  - "11"
install:
  - npm install
script:
  - npm test
before_script:
  - npm run build-storybook
before_deploy:
  - npm run build
deploy:
  - provider: npm
    email: $NPM_EMAIL
    api_key: $NPM_API_TOKEN
    skip_cleanup: true
    on:
      branch: master
notifications:
  email: false
