sudo: false
language: node_js
node_js:
  - "stable"
install:
  - npm install
script:
  - npm test
before_script:
  - npm run build-storybook
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  repo: joachimdalen/DevUI
  target_branch: gh-pages
  keep_history: true
  on:
    branch: master
notifications:
  email: false
