sudo: false
language: node_js
node_js:
- '8'
- '10'
cache:
  directories:
  - node_modules
before_install:
- npm update
install:
- npm install
script:
- npm test
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master